const quiz2Data = [
    {q: "What does RIDDOR stand for?", o: ["Risk Investigation and Disease Documentation Regulations", "Reporting of Injuries, Diseases and Dangerous Occurrences Regulations", "Recording of Industrial Deaths and Dangerous Operations Regulations", "Risk Identification and Dangerous Duties Record"], c: 1},
    {q: "According to RIDDOR, what must employers report to the HSE?", o: ["Only fatal accidents", "Accidents, near misses and ill health", "Equipment failures only", "Customer complaints"], c: 1},
    {q: "What information must be included on an accident record sheet?", o: ["Only the injured person's name", "Date, time, location, nature of injury, and account of the accident", "Just the date of the incident", "Only witness statements"], c: 1},
    {q: "What type of PPE was mentioned as being worn in the accident report example shown?", o: ["Hard hat only", "Safety goggles only", "Steel toe cap safety boots, overalls, bump cap, rough service gloves, and safety glasses", "Just safety boots"], c: 2},
    {q: "Who signs an accident record sheet?", o: ["Only the injured person", "The person completing the form and witnesses", "Just the service manager", "Only the HSE inspector"], c: 1},
    {q: "What does COSHH stand for?", o: ["Control of Safety and Health Hazards", "Control of Substances Hazardous to Health", "Chemical and Oil Safety Handling Hazards", "Control of Substance Handling and Operation Hazards"], c: 1},
    {q: "According to COSHH regulations, what must be done with hazardous substances?", o: ["They must be avoided completely", "They can be stored anywhere", "Substances must be marked with orange square with black symbols and listed", "They only need verbal warnings"], c: 2},
    {q: "What does the skull and crossbones hazard symbol indicate?", o: ["Flammable", "Toxic", "Corrosive", "Irritant"], c: 1},
    {q: "What does the flame symbol on a hazard label indicate?", o: ["Oxidising agent", "Corrosive", "Flammable", "Toxic"], c: 2},
    {q: "What does the 'X' symbol on hazard labels indicate?", o: ["Toxic", "Flammable", "Irritant", "Ecotoxic"], c: 2},
    {q: "What is a hazard?", o: ["The likelihood of harm happening", "Something that has the potential to cause harm or damage", "An accident that has already occurred", "A safety procedure"], c: 1},
    {q: "What is risk?", o: ["Something that causes harm", "A safety regulation", "The likelihood of the harm or damage actually happening", "A type of hazard"], c: 2},
    {q: "What does 'reasonably practicable' mean in risk assessment?", o: ["Completely eliminate all risks", "Can be carried out without incurring excessive effort or expense", "Ignore minor risks", "Only address major hazards"], c: 1},
    {q: "How many main steps are there in a risk assessment?", o: ["Three", "Four", "Five", "Six"], c: 2},
    {q: "What is Step 1 of a risk assessment?", o: ["Decide who might be harmed", "Identify the hazards", "Evaluate the risks", "Review the assessment"], c: 1},
    {q: "In Step 2 of risk assessment, who should you consider might be harmed?", o: ["Only employees", "Staff/colleagues, contractors, delivery operatives, customers, the general public, young people, and people with disabilities", "Just contractors", "Only the person doing the work"], c: 1},
    {q: "What should be done in Step 5 of a risk assessment?", o: ["Identify new hazards", "Train staff", "Review your assessment and update if necessary", "Purchase new equipment"], c: 2},
    {q: "Under which act must oils be disposed of in the correct manner?", o: ["Health and Safety at Work Act 1974", "The Waste (England and Wales) Regulations 2011 and Environmental Protection Act 1990 (EPA)", "RIDDOR 1995", "COSHH 2002"], c: 1},
    {q: "What is controlled waste?", o: ["Only household waste", "Any waste which should be disposed of to landfill", "Any waste that must be disposed of or kept in a way that is safe and will not pollute the environment or harm people", "Only commercial waste"], c: 2},
    {q: "What is an ecotoxic substance?", o: ["A substance that is flammable", "A substance that is harmful to the environment", "A substance that is toxic to humans only", "A substance that is corrosive"], c: 1},
    {q: "Which of the following is NOT listed as an example of controlled waste from an automotive workshop?", o: ["Old engine oil", "Oil filters", "Paper documents", "Batteries"], c: 2},
    {q: "Under the Environmental Protection (Duty of Care) Regulations 1991, controlled waste must only be transferred to whom?", o: ["Any waste collection company", "Someone who is authorised to take it, such as someone who holds a waste management licence or is a registered waste carrier", "The local council only", "Any recycling centre"], c: 1},
    {q: "What do red safety signs indicate?", o: ["A warning", "A mandatory instruction", "A prohibition (something you must not do)", "Safe conditions"], c: 2},
    {q: "What do blue safety signs indicate?", o: ["A prohibition", "A warning", "A mandatory instruction (something that you must do)", "Fire equipment location"], c: 2},
    {q: "What do yellow safety signs indicate?", o: ["Mandatory instructions", "Prohibitions", "A warning (hazard or danger)", "Safe exit routes"], c: 2}
];
