const quiz4Data = [
    {q: "What should you do if someone loses consciousness?", o: ["Give them something to drink", "Make sure the person is breathing and has a clear airway, maintain the airway and place casualty in recovery position", "Try to wake them up immediately", "Leave them alone until help arrives"], c: 1},
    {q: "What should you NOT do when dealing with a loss of consciousness casualty?", o: ["Place them in recovery position", "Maintain their airway", "Attempt to give anything by mouth", "Obtain emergency medical assistance"], c: 2},
    {q: "For how long should you cool a burn with cold water?", o: ["5 minutes", "10-20 minutes", "30 minutes", "1 hour"], c: 1},
    {q: "If it is a chemical burn, how long should flooding with cold water be done?", o: ["5 minutes", "10 minutes", "20 minutes", "As long as possible"], c: 2},
    {q: "What should you do if there are no clean dressings available for a burn?", o: ["Use any cloth available", "Leave it uncovered", "Use dirty bandages", "Apply ointment directly"], c: 1},
    {q: "What should you NEVER do with an object stuck in the eye?", o: ["Seek medical help", "Wash hands with soap and water", "Touch anything that is stuck in the eye", "Ask the casualty to lie down"], c: 2},
    {q: "How should you locate an object in the eye?", o: ["By rubbing the eye", "By gently lifting the eye lid and asking the casualty to look up and down and to the side until you see it", "By using fingers to search", "By flushing with any liquid"], c: 1},
    {q: "What should you NOT use as ointment on wounds if the skin is broken?", o: ["Clean water", "Sterile dressing", "Ointment", "Clean paper towel"], c: 2},
    {q: "What is the focus of the Level 3 Diploma?", o: ["Basic vehicle maintenance", "The diagnosis and repair of light vehicles with advanced technology systems", "Only electrical systems", "Heavy vehicle repair"], c: 1},
    {q: "What approach should you develop for diagnostic and repair work at Level 3?", o: ["Random testing approach", "A systematic approach", "Trial and error method", "Guesswork approach"], c: 1},
    {q: "What does 'systematic' mean in the context of diagnostic work?", o: ["Working quickly", "Planning a job so that you do things in order", "Using expensive tools", "Working alone"], c: 1},
    {q: "What does 'first time fix' mean?", o: ["Fixing the cheapest problem first", "Working as fast as possible", "Getting the repair right first time", "Using the first tool you find"], c: 2},
    {q: "What sections are included at the start and end of each chapter in the book?", o: ["Glossary and index", "Before you start and Before you finish", "Introduction and conclusion", "Summary and review"], c: 1},
    {q: "What topics are covered in the 'Before you start' sections?", o: ["Pricing and invoicing", "Safe working, electronic and electrical safety procedures, operation of systems, information sources, and tooling", "Customer complaints", "Workshop management"], c: 1},
    {q: "According to Table 1.4, what does Chapter 2 cover?", o: ["Engine systems", "Diagnosis and rectification of light vehicle chassis system faults", "Electrical systems only", "Transmission systems"], c: 1},
    {q: "What does EPB stand for in Chapter 2 topics?", o: ["Engine Power Brake", "Electronic Parking Brake", "Emergency Power Braking", "Electronic Performance Brake"], c: 1},
    {q: "What does EBD stand for?", o: ["Engine Brake Distribution", "Electronic Brake Diagnostics", "Electronic Brake force Distribution", "Emergency Braking Device"], c: 2},
    {q: "What does TCS stand for?", o: ["Temperature Control System", "Transmission Control System", "Traction Control Systems", "Turbo Charging System"], c: 2},
    {q: "What is Chapter 3 primarily about?", o: ["Chassis systems", "Diagnosis and rectification of light vehicle engine faults", "Electrical systems", "Transmission systems"], c: 1},
    {q: "What does Chapter 4 cover?", o: ["Engine systems", "Chassis systems", "Diagnosis and rectification of light vehicle auxiliary electrical faults", "Transmission systems"], c: 2},
    {q: "What is a 'fault' according to the key terms?", o: ["A symptom of a problem", "Something that is responsible for an undesirable situation or event", "A customer complaint", "A warning light"], c: 1},
    {q: "What is a 'symptom' according to the key terms?", o: ["The actual fault", "The repair procedure", "A sign that indicates a certain situation, especially an undesirable situation", "A diagnostic tool"], c: 2},
    {q: "What is the correct diagnostic principle regarding faults and symptoms?", o: ["Fix the symptom, not the fault", "Always fix the fault and not the symptom", "Symptoms and faults are the same thing", "Fix whichever is easier"], c: 1},
    {q: "Before beginning any diagnosis, what should you do first?", o: ["Start testing immediately", "Order new parts", "Gather as much information as possible by carefully questioning the customer", "Check online forums"], c: 2},
    {q: "What type of questions should you ask the customer during diagnosis?", o: ["Closed questions only", "General, open questions", "Technical questions they won't understand", "No questions - just diagnose"], c: 1}
];
